# Generated by Django 5.1.2 on 2024-10-26 23:31

import django.core.validators
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_alter_food_harga_alter_restaurant_id"),
        ("resto_preview", "0010_alter_rating_score_alter_rating_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together={("user", "restaurant")},
        ),
        migrations.AddField(
            model_name="follow",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rating",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="rating",
            name="score",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ]
            ),
        ),
        migrations.AlterUniqueTogether(
            name="follow",
            unique_together={("user", "restaurant")},
        ),
    ]
